# https://taskfile.dev

version: "3"

vars:
  PLAINTEXT: "Hello, world!"
  IV_B64: "L4GNQGz48epdIiVCc2MboQ=="
  CIPHERTEXT_B64: "mrH+LB63tYaVm7ZG3uFoaw=="

tasks:
  default:
    cmds:
      - "uv run python -m pad_tickler"

  start-demo-api:
    cmds:
      - uv run python -m demo_api.main

  demo-encrypt:
    cmds:
      - 'curl -s -X POST http://localhost:8000/api/encrypt -H "Content-Type: application/json" -d "{\"plaintext\": \"{{.PLAINTEXT}}\"}" | jq'

  demo-validate:
    cmds:
      - 'curl -s -X POST http://localhost:8000/api/validate -H "Content-Type: application/json" -d "{\"ciphertext_b64\": \"{{.CIPHERTEXT_B64}}\"}" | jq'

  test:
    cmds:
      - "uv run pytest"

  clean:
    cmds:
      - "rm -rf __pycache__"
      - "rm -rf demo_api/__pycache__"
      - "rm -rf pad_tickler/__pycache__"
      - "rm -rf .pytest_cache"
      - "rm -rf .ruff_cache"
      - "rm -rf .venv"
