name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Python setup
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --group dev --group demo
          uv pip install -e .

      - name: Run linting
        run: task lint

      - name: Test build
        run: task build

      - name: Test CLI installation
        run: uv run padtickler --help
