name: Release Test

on:
  push:
    branches:
      - main
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release-test:
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release-test.outputs.released }}
      version: ${{ steps.release-test.outputs.version }}
      tag: ${{ steps.release-test.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python setup
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --group dev --group demo
          uv pip install -e .

      - name: Build package
        run: uv run task build

      - name: Semantic Release
        id: release-test
        uses: python-semantic-release/python-semantic-release@4d4cb0ab842247caea1963132c242c62aab1e4d5 # v10.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          verbosity: 2
          build: false
          commit: false
          push: false

  publish-test:
    # https://packaging.python.org/guides/using-testpypi/
    name: Publish to Test PyPI
    needs: release-test
    if: needs.release-test.outputs.released == 'true' && github.event_name != 'merge_group'
    runs-on: ubuntu-latest
    environment:
      name: publish-test
      url: https://test.pypi.org/project/padtickler/
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Python setup
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
        with:
          enable-cache: true

      - name: Build package
        run: uv run task build

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          repository-url: https://test.pypi.org/legacy/
          attestations: true
